### ISSUE TITLE
Update Babel

### ISSUE THREAD

**Issue by williamcosta** [getninjas/dhalsim-js#44]
We need to update Babel to fix an error we're having in the Jest update in the PR #40 .

![Screen Shot 2019-05-07 at 09 36 32](https://user-images.githubusercontent.com/6557202/57299675-884d5a00-70ab-11e9-9405-65ebc6f62803.png)

**Comment by iondrimba** [comment]
Thanks for the info @williamcosta 👍

**Comment by williamcosta** [comment]
Update is done in the PR #45
